name: risto_widgets
description: "A Flutter library with customizable UI widgets for buttons, expandable list tiles, and more."
version: 0.1.0+4
homepage: "https://github.com/ristocloud-group/app-lib-risto-widgets"

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  lottie: ^3.1.2
  expandable: ^5.0.1
  font_awesome_flutter: ^10.7.0
  html2md: ^1.3.2
  cached_network_image: ^3.4.1
  flutter_markdown: ^0.7.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ristocloudgroup.lib.risto_widgets
        pluginClass: RistoWidgetsPlugin
      ios:
        pluginClass: RistoWidgetsPlugin
      linux:
        pluginClass: RistoWidgetsPlugin
      macos:
        pluginClass: RistoWidgetsPlugin
      windows:
        pluginClass: RistoWidgetsPluginCApi